# Generated by Django 5.1.1 on 2024-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_transaction_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.BigIntegerField(editable=False),
        ),
    ]
